### ISSUE TITLE
Cannot create boycott, Invalid alternative IDs error

### ISSUE THREAD

**Issue by daliovic** [palestirnative/palestirnative#61]
**Describe the bug**
Cannot create boycott, Invalid alternative IDs error

**To Reproduce**
1. Go to '/boycott/form'
2. Fill the form
3. Click Submit
4. See error `Invalid alternative IDs`

**Expected behavior**
A boycott should be added

**Screenshots**
<img width="1538" alt="image" src="https://github.com/palestirnative/palestirnative/assets/30472228/68528c55-ab0a-474b-a246-c102e68a5af0">

**Comment by daliovic** [comment]
@shiraz27 I tried this on multiple devices and envs as well as the staging and I am still getting that error

**Comment by shiraz27** [comment]
[fix: Invalid alternative IDs](https://github.com/palestirnative/palestirnative/pull/74/commits/5964fb104bde66dffcc7bf15c64e1e45592239a4)
