### ISSUE TITLE
Navigation Bar Disappears on Language Change in Staging Environment

### ISSUE THREAD

**Issue by daliovic** [palestirnative/palestirnative#70]
## Describe the bug:
When a user changes the language on any page within the staging environment, the navigation bar disappears. This issue persists until the page is reloaded.

## Steps to Reproduce:
1. Navigate to any page within the staging environment.
2. Use the language selector to change the current language.
3. Observe that the navigation bar is no longer visible.
4. Reload the page to see the navigation bar reappear.

## Expected behavior:
The navigation bar should remain visible and functional after changing the language, without the need for a page refresh.

## Actual behavior:
The navigation bar disappears when the language is changed and only reappears after a page refresh.

## Screenshots:
![Navigation Bar Issue](https://github.com/palestirnative/palestirnative/assets/30472228/6702c0fb-cc4e-48d3-a189-a4270f17ecc1)

## Environment:
- Staging

## Additional context:
This issue does not occur in the production environment.

**Comment by shiraz27** [comment]
This should be closed by this PR https://github.com/palestirnative/palestirnative/pull/73
 feel free to reopen if this reoccurs
